### ISSUE TITLE
WebGL(Not work)

### ISSUE THREAD

**Issue by Avatarchik** [codecoding/SQLite4Unity3d#24]
Hi!)
Mac Os 
Unity3d 5.1.2
x86 sqlite.dll
Error
http://monosnap.com/image/E9L67gaO03VtV7RIuzXhCxqhCjYz3b

need to build with DLOPEN_SUPPORT=1 to get dlopen support in asm.js
localhost/:34 need to build with DLOPEN_SUPPORT=1 to get dlopen support in asm.jsModule.printErr @ localhost/:34
localhost/:34 warning: a problem occurred in builtin C++ name demangling; build with  -s DEMANGLE_SUPPORT=1  to link in libcxxabi demanglingModule.printErr @ localhost/:34
UnityConfig.js:76 Invoking error handler due to
Uncaught abort("need to build with DLOPEN_SUPPORT=1 to get dlopen support in asm.js") at Error
    at jsStackTrace (http://localhost:53253/Release/Main.js:1187:13)
    at stackTrace (http://localhost:53253/Release/Main.js:1204:22)
    at abort (http://localhost:53253/Release/Main.js:3697320:44)
    at _dlopen (http://localhost:53253/Release/Main.js:6371:7)
    at __ZN6il2cpp2os13LibraryLoader18LoadDynamicLibraryERKNSt3__112basic_stringIcNS2_11char_traitsIcEENS2_9allocatorIcEEEE [il2cpp::os::LibraryLoader::LoadDynamicLibrary?S(undefined?N?&)] (http://localhost:53253/Release/Main.js:51847:8)
    at __ZN6il2cpp2vm14PlatformInvoke7ResolveERK16PInvokeArguments [il2cpp::vm::PlatformInvoke::Resolve(PInvokeArguments?&)] (http://localhost:53253/Release/Main.js:64947:8)
    at __Z30il2cpp_codegen_resolve_pinvokeIPFiPhPiiiEET_PKcS6_20Il2CppCallConvention13Il2CppCharSetib [undefined il2cpp_codegen_resolve_pinvoke<undefined?F?*, int, unsigned char*, int*, int, int>?T()] (http://localhost:53253/Release/Main.js:3626275:8)
    at _m6209 (http://localhost:53253/Release/Main.js:3003603:9)
    at _m2815 (http://localhost:53253/Release/Main.js:3003494:9)
    at _m58 (http://localhost:53253/Release/Main.js:2560966:2)
If this abort() is unexpected, build with -s ASSERTIONS=1 which can give more information.
:53253/Release/Main.js:10502 Uncaught abort("need to build with DLOPEN_SUPPORT=1 to get dlopen support in asm.js") at Error
    at jsStackTrace (http://localhost:53253/Release/Main.js:1187:13)
    at stackTrace (http://localhost:53253/Release/Main.js:1204:22)
    at abort (http://localhost:53253/Release/Main.js:3697320:44)
    at _dlopen (http://localhost:53253/Release/Main.js:6371:7)
    at __ZN6il2cpp2os13LibraryLoader18LoadDynamicLibraryERKNSt3__112basic_stringIcNS2_11char_traitsIcEENS2_9allocatorIcEEEE [il2cpp::os::LibraryLoader::LoadDynamicLibrary?S(undefined?N?&)] (http://localhost:53253/Release/Main.js:51847:8)
    at __ZN6il2cpp2vm14PlatformInvoke7ResolveERK16PInvokeArguments [il2cpp::vm::PlatformInvoke::Resolve(PInvokeArguments?&)] (http://localhost:53253/Release/Main.js:64947:8)
    at __Z30il2cpp_codegen_resolve_pinvokeIPFiPhPiiiEET_PKcS6_20Il2CppCallConvention13Il2CppCharSetib [undefined il2cpp_codegen_resolve_pinvoke<undefined?F?*, int, unsigned char*, int*, int, int>?T()] (http://localhost:53253/Release/Main.js:3626275:8)
    at _m6209 (http://localhost:53253/Release/Main.js:3003603:9)
    at _m2815 (http://localhost:53253/Release/Main.js:3003494:9)
    at _m58 (http://localhost:53253/Release/Main.js:2560966:2)
If this abort() is unexpected, build with -s ASSERTIONS=1 which can give more information.

**Comment by codecoding** [comment]
Sorry but this is not supported. You cannot use SQLite on the web browser.
